name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Cordova
        run: npm install -g cordova

      - name: Install dependencies
        run: npm install

      - name: Add Android
        run: cordova platform add android

      - name: Build APK
        run: cordova build android

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: TempKey-APK
          path: platforms/android/app/build/outputs/apk/debug/*.apk
